### ISSUE TITLE
Define own metadata

### ISSUE THREAD

**Issue by LeebPhil** [sane-city/wot-servient#41]
Hey guys,

i wanted to ask if it is possible to define own metadata, just like you can set a title from java code:    
```java
setTitle("title")
```
or is this only possible when loading from json?
To provide an example what i think it could/should look like: https://github.com/w3c/wot-discovery/blob/main/proposals/geolocation.md#static-location

Kind regards
Phil

**Comment by HeikoBornholdt** [comment]
Hey,

sorry for the late response. Currently, this is not possible (neither when reading a JSON/Thing Description, nor when writing). I can add a generic method (e.g., `setMetadata(String,Object)` or/and `addMetadata(String,Object)`) through which you can add your own metadata. Would this be ok for you?

**Comment by LeebPhil** [comment]
Hey @heikobornholdt ,  
  
no problem. This would be great if such a method exists!

Best reagrds  
Phil

**Comment by LeebPhil** [comment]
@heikobornholdt  
  
can you estimate how long it will take you until this feature is available?

**Comment by HeikoBornholdt** [comment]
This week
Am 28. Juni 2021, 12:30 +0200 schrieb LeebPhil ***@***.***>:

**Comment by LeebPhil** [comment]
@heikobornholdt 

Thank you!

**Comment by HeikoBornholdt** [comment]
I need a few more days. Sorry for the delay.
Am 30. Juni 2021, 16:17 +0200 schrieb LeebPhil ***@***.***>:

**Comment by LeebPhil** [comment]
@heikobornholdt 

no problem.

**Comment by LeebPhil** [comment]
@heikobornholdt  
  
any update on how long it will take?

**Comment by HeikoBornholdt** [comment]
Sorry for the delay and thank you for your patience. The last few days driving very busy.

I've merged the requested feature into the master branch. You can try it out by using version 1.16-SNAPSHOT.
Do not hesitate to contact me if you have any problems.
