### ISSUE TITLE
ObjectType for Events and Actions

### ISSUE THREAD

**Issue by LeebPhil** [sane-city/wot-servient#42]
Hey guys,  
  
i think it would be a great feature to have an ObjectType ``` "@type": "xyz"``` for Events and Actions, so Es and As can be used with ontologies.  
  
Best regars,  
Phil

**Comment by HeikoBornholdt** [comment]
I've added ObjectType for Events and Events with df608d0c0514c6dd0361797447d2222e1575fb74 into master.
