### ISSUE TITLE
CoAP support?

### ISSUE THREAD

**Issue by Citrullin** [sane-city/wot-servient#8]
It doesn't look like this is under active development, but I try to ask. 
Will you add CoAP support at some point?

**Comment by HeikoBornholdt** [comment]
Hi!,

CoAP support is already included (server and client).

https://github.com/sane-city/wot-servient/blob/master/doc/binding/coap.md

**Comment by Citrullin** [comment]
> 
> 
> Hi!,
> 
> CoAP support is already included (server and client).
> 
> https://github.com/sane-city/wot-servient/blob/master/doc/binding/coap.md

Ohh thanks. Okay, I need to look into it then. Ahh, okay, just a config, thanks. This is great! 👍 
And fast reply. Didn't expect that. Awesome! :)
/e Okay, maybe I should take a look into the code next time. ^^ My mistake.
